server:
  port: 9000

frontend:
  url: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**,public/**
      poll-interval: 1s
      quiet-period: 400ms
      log-condition-evaluation-delta: false
    livereload:
      enabled: true
  main:
    allow-circular-references: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.backend: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Security and CORS configuration
security:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000

# CORS configuration
# cors:
#   allowed-origins: http://localhost:3000
#   allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#   allowed-headers: "*"
#   allow-credentials: true