spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**,public/**
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.boot.devtools: DEBUG
    org.springframework.web: DEBUG 