server:
  port: 8080
frontend:
  url: localhost:3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    restart.poll-interval: 2s
    restart.quiet-period: 1s
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml